name: Build Chain

on: [pull_request]

jobs:
  build-chain:
    strategy:
      matrix:
        java-version: [8, 11]
      fail-fast: false
    runs-on: ubuntu-latest
    name: Maven Build
    steps:
      - name: Free disk space
        run: |
          df -h          
          sudo swapoff /swapfile
          sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt clean
          docker rmi $(docker image ls -aq) >/dev/null 2>&1
          df -h
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Install takari
        run: |
          wget -P $M2_HOME/lib/ext https://repo1.maven.org/maven2/io/takari/aether/takari-local-repository/0.11.3/takari-local-repository-0.11.3.jar
          wget -P $M2_HOME/lib/ext https://repo1.maven.org/maven2/io/takari/takari-filemanager/0.8.3/takari-filemanager-0.8.3.jar
          wget -P $M2_HOME/lib/ext https://repo1.maven.org/maven2/io/takari/maven/takari-smart-builder/0.6.1/takari-smart-builder-0.6.1.jar
      - name: Build Chain ${{ matrix.java-version }}
        id: build-chain
        uses: kiegroup/github-action-build-chain@v1.4
        with:
          parent-dependencies: 'optaweb-vehicle-routing'
          build-command: 'mvn -e -nsu install -Dfull -Prun-code-coverage -Pwildfly -Dcontainer=wildfly -Dcontainer.profile=wildfly -Dintegration-tests=true -Dmaven.test.failure.ignore=true -Pbusiness-central -Dgwt.compiler.localWorkers=1 -Dwebdriver.firefox.bin=/opt/tools/firefox-60esr/firefox-bin'
          build-command-upstream: |
            mvn -e --builder smart -T1C install -DskipTests -Dgwt.compiler.skip=true -Dgwt.skipCompilation=true -Denforcer.skip=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Drevapi.skip=true
            rm -rf ./*
          workflow-file-name: "pull_request.yml"
          archive-artifacts-path: |
            **/target/screenshots/**
            **/target/business-monitoring-webapp.war
            **/target/business-central*eap*.war
            **/target/business-central*wildfly*.war
            **/target/jbpm-server*dist*.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
                                                                                